#!/bin/bash

[[ -z $1 ]] &&
    {
        echo "usage: $0 <log>"
        exit 1
    }

function display()
{
    local FILE=$1

    loupe $FILE > /dev/null 2>&1 &
}

function display-report()
{
    local TEST=$1
    local DISP=FALSE

    while read line; do
        if [[ $line =~ $TEST ]]; then
            DISP=TRUE
        elif [[ $DISP == TRUE ]] && [[ $line =~ ^Test ]]; then
            DISP=FALSE
        fi

        [[ $DISP == TRUE ]] &&
            echo "$line"

    done < $LOG
}

function clear-display()
{
    killall loupe
}

function analyze()
{
    local T=$1
    echo ""
    echo "================================== Testing $T"
    echo ""

    display-report $T

    display $T/diff.png &

    while read -p "cmd: e/o/d/oc/dc/r/k/t/a/?: " cmd; do
        case "$cmd" in
            "?")
                echo ""
                echo "r  - display report"
                echo "e  - expected"
                echo "o  - output"
                echo "d  - diff"
                echo "oc - OpenCL output"
                echo "od - OpenCL diff"
                echo ""
                echo "k  - keep expected, move next"
                echo "t  - trash expected, move next"
                echo "a  - approve change, commit it, move next"
                echo ""
                ;;
            e)
                display $T/expected.png &
                continue
                ;;
            o)
                display $T/output.png &
                continue
                ;;
            d)
                display $T/diff.png &
                continue
                ;;
            oc)
                display $T/output-cl.png &
                continue
                ;;
            dc)
                display $T/diff-cl.png &
                continue
                ;;
            r)
                display-report $T
                continue
                ;;
            k)
                clear-display
                break
                ;;
            t)
                clear-display
                rm $T/expected.png
                break
                ;;
            a)
                clear-display
                rm $T/expected.png
                ./run $T
                git add $T/expected.png
                git commit -m "$T: Update expected output."
                break
                ;;
        esac
    done
}

LOG=$1

# Record in TESTS all failed tests

TESTS=()

T=""

while read line; do
    if [[ $line =~ Test ]]; then
        T=${line#Test}
    elif [[ -n $T ]] && [[ $line =~ FAILS: ]]; then
        TESTS+=($T)
        T=""
    fi
done < $LOG

# Analyze tests

for T in ${TESTS[*]}; do
    analyze $T
done
